apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler       
metadata:
  name: nginx-hpa
  namespace: front-ns
spec:
  maxReplicas: 10                     
  minReplicas: 5                     
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 70
