apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
  name: nginx
  namespace: front-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      imagePullSecrets:
      - name: ecr-secret
      
      affinity:                                   
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:                          
                - key: app
                  operator: In
                  values:
                  - front
              topologyKey: kubernetes.io/hostname
               
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        nodeTaintsPolicy: Honor
        labelSelector:                        
          matchLabels:                        
            app: front
                                    
      containers:
      - image: 070238434919.dkr.ecr.ap-northeast-2.amazonaws.com/nginx:v3.2
        name: nginx
        ports:
        - containerPort: 80

        livenessProbe:
          tcpSocket:       
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5  
          
        readinessProbe:
          httpGet:       
            path: /        
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          
        resources:
         # requests:
         #   memory: "16Mi"
         #   cpu: "25m"
          limits:
            memory: "32Mi"    
            cpu: "150m"
